feat: Add indexer healthcheck

diff --git a/indexer/Dockerfile b/indexer/Dockerfile
--- a/indexer/Dockerfile
+++ b/indexer/Dockerfile
@@ -26,9 +26,27 @@ RUN cargo build --release -p indexer
 FROM debian:bookworm-slim as runtime
 WORKDIR /indexer-app
 
-RUN apt update && apt install -yy openssl ca-certificates jq
+RUN apt update && apt install -yy openssl ca-certificates jq netcat-traditional httpie
 
 COPY --from=builder /tmp/indexer/target/release/indexer .
 COPY ./indexer/entrypoint.sh ./entrypoint.sh
 RUN chmod +x ./entrypoint.sh
+
+EXPOSE 3030
+
+HEALTHCHECK --interval=20s --timeout=30s --retries=200 \
+  CMD nc -zv localhost 3030 && \
+      sh -c 'while true; do \
+        resp=$(http post http://localhost:3030 jsonrpc=2.0 method=status params:="[]" id=dontcare); \
+        if [ $? -ne 0 ]; then \
+          echo "Request failed with error: $resp" >&2; \
+          exit 1; \
+        fi; \
+        sync_status=$(echo $resp | jq -r ".result.sync_info.syncing"); \
+        if [ "$sync_status" = "false" ]; then \
+          exit 0; \
+        fi; \
+        sleep 1; \
+      done'
+
 ENTRYPOINT [ "./entrypoint.sh" ]
